import "dotenv/config";
import { loadBriefingConfig } from "./config.js";
import { requireEnvironment } from "./environment.js";
import { sendBriefing } from "./mail.js";
import { createBriefingModule } from "./modules/registry.js";
import type { BriefingModule, CollectedBriefingModule } from "./modules/types.js";
import { summarizeWithOllama } from "./ollama.js";
import { buildDailyBriefingPrompt } from "./prompt.js";

async function main() {
    const config = await loadBriefingConfig();
    const model = requireEnvironment("BRIEFING_MODEL");
    const modules = config.modules.map((moduleName) => createBriefingModule(moduleName, model));

    console.log(`Model: ${model}`);
    console.log(`Enabled modules: ${config.modules.join(", ")}`);

    const collectedModules = await Promise.all(modules.map(collectModule));
    const prompt = buildDailyBriefingPrompt(collectedModules);

    console.log("\n=== Structured Briefing Data ===\n");
    console.log(
        collectedModules.map(({ id, heading, data }) => ({
            id,
            heading,
            data,
        })),
    );

    console.log("\n=== AI Daily Briefing ===\n");

    const generatedBriefing = await summarizeWithOllama(model, prompt, (token) => process.stdout.write(token));
    const footer = `This briefing has been AI-generated by **${model}**.`;
    const briefing = `${generatedBriefing.trim()}\n\n---\n\n${footer}`;

    console.log(`\n\n---\n\n${footer}`);

    await sendBriefing(briefing);
}

async function collectModule(module: BriefingModule): Promise<CollectedBriefingModule> {
    const { collect, ...metadata } = module;

    try {
        const output = await collect();

        return {
            ...metadata,
            heading: output.heading,
            data: output.data,
        };
    } catch (error) {
        console.error(`Failed to collect ${module.label}:`, error);

        return {
            ...metadata,
            heading: module.fallbackHeading,
            data: null,
        };
    }
}

main().catch((error) => {
    console.error(error);
    process.exit(1);
});
