import "dotenv/config";
import { daysAgo, parseCliArgs } from "./cli.js";
import { getGitSummary } from "./git.js";
import { getWeatherSummary } from "./weather.js";
import { getNews } from "./news/index.js";
import { translateNewsTitles } from "./news/translate-news.js";
import { summarizeWithOllama } from "./ollama.js";
import { buildDailyBriefingPrompt } from "./prompt.js";
import { sendBriefing } from "./mail.js";

async function main() {
    const { repoPath, model, mainGitDays, branchGitDays } = parseCliArgs();

    console.log(`Collecting Git activity from: ${repoPath}`);
    console.log(`Model: ${model}`);
    console.log(`Git windows: main ${mainGitDays} day(s), branches ${branchGitDays} day(s)`);

    const [gitSummary, weatherSummary, rawNewsSummary] = await Promise.all([
        safeCollect("Git activity", () => getGitSummary(repoPath, daysAgo(mainGitDays), daysAgo(branchGitDays))),
        safeCollect("weather", () => getWeatherSummary()),
        safeCollect("news", () => getNews()),
    ]);

    let newsSummary = rawNewsSummary;

    if (rawNewsSummary) {
        const translatedGeneralNews = await safeCollect("news title translation", () => translateNewsTitles(rawNewsSummary.general, model));

        if (translatedGeneralNews) {
            newsSummary = {
                ...rawNewsSummary,
                general: translatedGeneralNews,
            };
        }
    }

    // console.log("\n=== Structured Git Data ===\n");
    // console.log(JSON.stringify(gitSummary, null, 2));

    // console.log("\n=== Structured Weather Data ===\n");
    // console.log(JSON.stringify(weatherSummary, null, 2));

    // console.log("\n=== Structured News Data ===\n");
    // console.log(JSON.stringify(newsSummary, null, 2));

    const prompt = buildDailyBriefingPrompt(gitSummary, weatherSummary, newsSummary, {
        mainGitDays,
        branchGitDays,
    });

    console.log("\n=== AI Daily Briefing ===\n");

    const generatedBriefing = await summarizeWithOllama(model, prompt, (token) => process.stdout.write(token));

    const footer = `This briefing has been AI-generated by **${model}**.`;

    const briefing = `${generatedBriefing.trim()}\n\n---\n\n${footer}`;

    console.log(`\n\n---\n\n${footer}`);

    await sendBriefing(briefing);
}

main().catch((error) => {
    console.error(error);
    process.exit(1);
});

async function safeCollect<T>(label: string, collector: () => Promise<T>): Promise<T | null> {
    try {
        return await collector();
    } catch (error) {
        console.error(`Failed to collect ${label}:`, error);
        return null;
    }
}
